### ISSUE TITLE
"Error: The `asyncapi` field is missing."

### ISSUE THREAD

**Issue by mihailDanchenko** [Pakisan/jasyncapi-idea-plugin#48] opened 2022-08-26 13:18 UTC
When try to using Intelllij Idea extansion I see that:
![image](https://user-images.githubusercontent.com/40184152/186911045-589573b7-fc36-4b81-abae-a733bb10df00.png)

Also, when I check inspection profile for AsyncAPI the link in description are broken.
![image](https://user-images.githubusercontent.com/40184152/186911522-9b93f495-ebe7-4831-aa02-75a5e157e24a.png)
The link is: https://raw.githubusercontent.com/asyncapi/asyncapi/master/versions/2.0.0/schema.json and it 404

Use 1.6.0+idea2021 
![image](https://user-images.githubusercontent.com/40184152/186912235-f8317765-8642-40ec-9bd5-c7cf40ea7154.png)

**Comment by philCryoport** [comment] 2022-10-04 18:00
Is this a duplicate of #35 ?

**Comment by Pakisan** [comment] 2022-10-04 20:39
@mihailDanchenko Windows?

@philCryoport yes, looks like duplicate

**Comment by Pakisan** [comment] 2022-10-15 22:13
@mihailDanchenko hi.

Can you check it in new release?

[jasyncapi-idea-plugin-1.7.1+idea2021.zip](https://github.com/Pakisan/jasyncapi-idea-plugin/files/9793208/jasyncapi-idea-plugin-1.7.1%2Bidea2021.zip)

**Comment by Pakisan** [comment] 2022-10-19 09:25
Fixed in [1.7.1](https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.7.1%2Bidea2021). Will be published to plugins within 2 days, after moderation.

**Closed by Pakisan** 2022-10-19 09:25 UTC
Labels: bug, help wanted
