### ISSUE TITLE
"Error: The `asyncapi` field is missing." when trying preview of sample schema

### ISSUE THREAD

**Issue by koenigroland** [Pakisan/jasyncapi-idea-plugin#35] opened 2022-04-18 20:47 UTC
When I try to preview the file with "Built-In Preview" of intellij or "Edge-Preview" there is only a page showing the error  "Error: The `asyncapi` field is missing.".
Instead I would expect to see the generated API-Doc.

Steps to reproduce.
1. Right-Click in project folder. New ->AsyncAPI Schema
2. Name the file test.json or test.yaml (tried both)
3. open the file and push one of the preview buttons (Edge or Built-In)
4. Preview-Window or browser shows the error "Error: The `asyncapi` field is missing."

Used System:
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022

Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    ...
    com.asyncapi.plugin.idea (1.5.0+idea2021)
    ...

The same procedure works on my colleague's macbook without errors, so I guess it's a problem with my operating system.

**Comment by Pakisan** [comment] 2022-04-27 21:41
@koenigroland 

> The same procedure works on my colleague's macbook without errors, so I guess it's a problem with my operating system.
At first look, looks so. I didn't reproduce problem on my Mac. Will try to check it on PC

 > "Error: The asyncapi field is missing.".
 Error still appear for all schemas which you try to preview?

**Comment by philCryoport** [comment] 2022-05-31 23:05
Hi folks, checking in ... any updates on this?

**Comment by koenigroland** [comment] 2022-06-01 10:43
Hi @Pakisan,
sorry for the late answer. Tried again with

IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022

Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
...
    com.asyncapi.plugin.idea (1.5.0+idea2021)
...

but still the same error.
I have checked the files located in the referenced url e.g.
url: 'http://localhost:63342/asyncapi/resources?schemaUrl=C:\Users\myuser\AppData\Local\Temp\jasyncapi-idea-plugin-1654078901632.yaml and they look like the files in intellij.
The only difference I found was, that the created yaml files had the same line ending as the file in intellij. The json files were CRLF no matter what was configured in intellij.
Maybe your parser is expecting LF instead of CRLF somewhere?

**Comment by tiger-seo** [comment] 2022-07-13 10:55
+1 to the bug: my colleague with Mac can preview asyncapi spec just fine, but at my workstation, with Windows, I observe the following error `Error: The asyncapi field is missing.`

**Comment by Pakisan** [comment] 2022-10-15 22:12
@tiger-seo @koenigroland hi.

Can you check it in new release?

[jasyncapi-idea-plugin-1.7.1+idea2021.zip](https://github.com/Pakisan/jasyncapi-idea-plugin/files/9793208/jasyncapi-idea-plugin-1.7.1%2Bidea2021.zip)

**Comment by Pakisan** [comment] 2022-10-19 09:25
Fixed in [1.7.1](https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.7.1%2Bidea2021). Will be published to plugins within 2 days, after moderation.

**Comment by CKATEPTb** [comment] 2022-10-19 19:58
> Fixed in [1.7.1](https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.7.1%2Bidea2021). Will be published to plugins within 2 days, after moderation.

![image](https://user-images.githubusercontent.com/33106029/196791502-360d438f-18a4-4432-8e92-d25c0de6ee7f.png)

not work for me

**Comment by Pakisan** [comment] 2022-10-19 20:03
@CKATEPTb

After IDEA relaunch behaviour will be same?

**Comment by CKATEPTb** [comment] 2022-10-19 20:06
I just managed to get this to work. By downloading the archive sent above. Downloaded from releases does not work. I have restarted IntellijIDEA several times, including trying as administrator

**Comment by Pakisan** [comment] 2022-10-19 20:11
@CKATEPTb wow it's strange.

Will diff builds.

Thank you for feedback

**Comment by CKATEPTb** [comment] 2022-10-19 20:17
Thank you for fixing the bug 10 hours before I needed this plugin❤

**Comment by Pakisan** [comment] 2022-10-19 20:22
> Downloaded from releases does not work. I have restarted IntellijIDEA several times, including trying as administrator

@CKATEPTb will fix it tonigh.

Looks like I built plugin from release branch before merging of fix into it

**Comment by CKATEPTb** [comment] 2022-10-19 20:27
It's a shame that this will delay moderation. In general, it happens. Thx again

**Comment by Pakisan** [comment] 2022-10-19 21:01
@CKATEPTb I re-uploaded release.

https://plugins.jetbrains.com/plugin/15673-asyncapi/versions/stable/240448

Can you delete and install plugin, when you will have free time? Unfortunately I don't have Windows to check it

**Comment by CKATEPTb** [comment] 2022-10-19 21:14
> @CKATEPTb I re-uploaded release.
> 
> https://plugins.jetbrains.com/plugin/15673-asyncapi/versions/stable/240448
> 
> Can you delete and install plugin, when you will have free time? Unfortunately I don't have Windows to check it

Work fine

**Comment by Pakisan** [comment] 2022-10-19 21:17
@CKATEPTb thanks for checking!

**Closed** 2022-10-21 08:56 UTC
Labels: bug, help wanted

**Comment by koenigroland** [comment] 2022-10-28 15:52
Works for me too now.
Thank you very much!

Tested with:
    IntelliJ IDEA 2022.2.3 (Ultimate Edition)
    Build #IU-222.4345.14, built on October 5, 2022
    
    Runtime version: 17.0.4.1+7-b469.62 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
    Windows 10 10.0
